layout_spectrum: 0.178812
color:
  saturation: 0.816322
  brandStrength: 1
  lightness: 0.4137989
  rhythmicContrast: 0.0883581
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.3582117
name: bestwebsiteever
